### ISSUE TITLE
Can't install dependencies using yarn

### ISSUE THREAD

**Issue by haipham23** [coryhouse/react-slingshot#412] opened 2017-04-07 16:44 UTC
Node version: 6.9.1
npm version: 3.10
yarn version: 0.22.0
Operating system: MacOs

Command line used: yarn

It throws the below error:
```
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://artifacts.bos.rapid7.com/nexus/content/groups/npm-all/extract-text-webpack-plugin/-/extract-text-webpack-plugin-2.1.0.tgz: getaddrinfo ENOTFOUND artifacts.bos.rapid7.com artifacts.bos.rapid7.com:443".
```

**Comment by kwelch** [comment] 2017-04-07 17:07
Is this the only repo that is not working using yarn? This doesn't appear to be react-slingshot specific.

**Comment by coryhouse** [comment] 2017-04-07 23:44
That's a network issue. Closing.

**Comment by alveshelio** [comment] 2017-05-10 13:59
Hi @coryhouse,

I am facing the same issue as @haipham23, and this only happens in this repository. When I run yarn in another repository I have no issues with the network.

**Comment by mikedevita** [comment] 2017-05-10 14:33
👍  I am another person experiencing this same issue on two different machines on two different networks.

**Comment by kwelch** [comment] 2017-05-10 14:35
Reopening to initialize further investigation.

**Comment by coryhouse** [comment] 2017-05-11 00:13
For those reporting, please provide all the necessary details about your system. 

Node version
npm version
yarn version
Operating system
Command line used

**Comment by alveshelio** [comment] 2017-05-11 01:53
Hi @coryhouse,

Thank you for taking the time to review this issue.

Here's what I' using
Node Version: **7.8.0**
NPM version: **4.2.0**
yarn version: **0.23.3**
OS: Mac Sierra **10.12.4**
Command Line used: **yarn install**

**Comment by mikedevita** [comment] 2017-05-11 16:41
**Node version:** 6.10.1
**npm version:** 3.10.10
**yarn version:** 0.23.4
**Operating system:** OS X Sierra
**Command line used:** `yarn install` or `yarn add <some_module>`

if i run `npm i <some_module>` it works fine.

**Comment by kwelch** [comment] 2017-05-11 20:19
may want to blank out (& regen) that authtoken.

**Comment by mikedevita** [comment] 2017-05-11 21:34
its behind a corp firewall, good luck getting in lol.

**Comment by nickytonline** [comment] 2017-05-12 02:00
This really is a network related issue so closing.

If you still have issues with yarn and you do not think it is network related, please [open an issue with them](https://github.com/yarnpkg/yarn/issues)

**Comment by nickytonline** [comment] 2017-05-15 12:46
Reopening as this is affecting CI as well.

**Comment by nickytonline** [comment] 2017-05-15 12:47
For example, https://travis-ci.org/coryhouse/react-slingshot/jobs/232185638

**Comment by nickytonline** [comment] 2017-05-15 12:50
@kwelch, you mentioned that a yarn upgrade fixed this. Can you throw a PR up for that?

**Closed** 2017-05-15 12:51 UTC

**Comment by kwelch** [comment] 2017-05-15 12:53
Since the change only affects the `yarn.lock` and there is nothing to review there I just pushed against master.

**Comment by nickytonline** [comment] 2017-05-15 12:55
Just curious why we had to update the yarn.lock file. Were some dependencies in another PR not added to the yarn.lock? Even if they weren't, CI would have simply upgraded the yarn.lock in each CI build.

**Comment by kwelch** [comment] 2017-05-15 12:57
Yarn lock is not edited in CI by design. It is suppose to read deps as they were installed on the client. It is possible a dep was not included in a past PR. We may want to add that to the PR review checklist: ensuring yarn lock is updated.

**Comment by nickytonline** [comment] 2017-05-15 13:04
If you run `yarn `though and `yarn.lock` is not up to date, it updates the
`yarn.lock` file. In the context of CI it gets scrapped at the end of the
build. On your local, you'll see that the `yarn.lock` has changed.

That's the behaviour I've seen on my projects when someone forgets to
update it or they did `npm install` instead of `yarn`. That's why I'm still
perplexed that the upgrade fixed CI.

**Comment by kwelch** [comment] 2017-05-15 13:29
It could have been related to a bad link to a server in the file.

**Comment by coryhouse** [comment] 2017-05-15 14:54
For reasons like these I'm eager to drop yarn for when in npm 5 is
released. Thanks guys!

**Comment by GeorgeKaraszi** [comment] 2018-09-01 15:43
Hey this is kind of an old issue. But I came across the same exact problem. In my case it had todo with how my Mac was caching DNS's.

After running `sudo killall -HUP mDNSResponder` I was able to install without issue.

More related commands to flushing your given OS network cache:
https://documentation.cpanel.net/display/CKB/How+To+Clear+Your+DNS+Cache

**Comment by bsedefian** [comment] 2018-09-02 04:41
Tried what you suggested GeorgeKaraszi, didn't work for me.

**Comment by nickytonline** [comment] 2018-09-02 13:57
Glad you both got it sorted out.

**Comment by bsedefian** [comment] 2018-09-03 11:40
I think you misinterpreted my comment to say that it DID work for me -- it didn't. However since yesterday morning it seems that the issue has resolved itself.

**Comment by nickytonline** [comment] 2018-09-03 12:17
Oops, my bad. Glad it's working now though @bsedefian. Did you do any other additional steps to get it working?

**Comment by bsedefian** [comment] 2018-09-03 12:27
Not a thing. Didn't delete proxy, didn't reinstall, didn't reset router, nothing.
