### ISSUE TITLE
t is not a function on production build.

### ISSUE THREAD

**Issue by Penthious** [coryhouse/react-slingshot#439] opened 2017-05-30 19:35 UTC
I am getting a error when I run `npm run build`, Webpack compiles and everything works but when I go to the site that its hosted on I get `t is not a function`

Everything on development works just fine its only when I run it in production mode....
![screen shot 2017-05-30 at 1 13 47 pm](https://cloud.githubusercontent.com/assets/12500410/26600725/55dfc146-453a-11e7-8c75-173527c0a846.png)

Any Ideas on what could be going on?

Gist of my webpack.config.prod.js and package.json
https://gist.github.com/Penthious/2382b1619f5bb481d8cf0cdb0ce5c1e5

Node version: v7.8.0

npm version: v4.2.0

Operating system: linux

Command line used: npm run build

**Comment by coryhouse** [comment] 2017-05-30 19:41
Is this an issue with Slingshot out of the box?

**Comment by Penthious** [comment] 2017-05-30 19:48
I dont think so, I am using react slingshot as my base and built off of it. But the webpack has pretty much stayed the same, only added babel-polyfill to it but I commented it out and it still gives me that error. Not sure why its breaking. I run `npm run start` and it works just fine but if I run it in production thats when I get the error.

**Comment by Penthious** [comment] 2017-05-30 19:49
Ill try to see if it gives me the same error if I use a base version of react slingshot, one moment.

**Comment by Penthious** [comment] 2017-05-30 20:00
Yea its just my code it seems like. Base react slingshot works just fine on my production server

**Comment by coryhouse** [comment] 2017-05-30 20:02
Okay, closing then since not a bug in Slingshot - I'd look at line 20 in main.js though. :)

**Closed by coryhouse** 2017-05-30 20:02 UTC

**Comment by Penthious** [comment] 2017-05-30 21:21
I figured it out, In my .bablerc I wasnt transforming my decorators in the production build like I was in the development build.
