### ISSUE TITLE
Newbe hot reloading problem on Windows

### ISSUE THREAD

**Issue by czlowieku** [coryhouse/react-slingshot#306] opened 2016-11-09 23:23 UTC
Node version:  5.12.0 (tried with newest one as well)

npm version: 3.8.6

Operating system: Windows 10

Command line used: npm start -s

Steps to reproduce:

When I run npm start -s the app starts fine, when I change and save something it hot reloads fine but when I do this again it gives me this in console and hot reloading does not work anymore:

```
 events.js:154
          throw er; // Unhandled 'error' event
          ^
    
    Error: listen EADDRINUSE :::8888
        at Object.exports._errnoException (util.js:893:11)
        at exports._exceptionWithHostPort (util.js:916:20)
        at Server.__dirname.Server.Server._listen2 (net.js:1246:14)
        at listen (net.js:1282:10)
        at Server.__dirname.Server.Server.listen (net.js:1378:5)
        at EventEmitter.listen (E:\Dev\React\ReactPlayGround\node_modules\webpack-bundle-analyzer\node_modules\express\lib\application.js:617:24)
        at Object.startServer (E:\Dev\React\ReactPlayGround\node_modules\webpack-bundle-analyzer\lib\viewer.js:57:14)
        at BundleAnalyzerPlugin.startAnalyzerServer (E:\Dev\React\ReactPlayGround\node_modules\webpack-bundle-analyzer\lib\BundleAnalyzerPlugin.js:78:12)
        at analyzeFn (E:\Dev\React\ReactPlayGround\node_modules\webpack-bundle-analyzer\lib\BundleAnalyzerPlugin.js:57:24)
        at Timeout._onTimeout (E:\Dev\React\ReactPlayGround\node_modules\webpack-bundle-analyzer\lib\BundleAnalyzerPlugin.js:69:11)
        at tryOnTimeout (timers.js:224:11)
        at Timer.listOnTimeout (timers.js:198:5)
    ERROR: "open:src" exited with 1.
```
It seems like the port for the dev server is taken but why it works at the begging? 
I am using Visual Studio Code if that makes any difference.
Please help, thanks.

**Comment by nickytonline** [comment] 2016-11-10 02:31
Duplicate of #301.

**Closed by nickytonline** 2016-11-10 02:31 UTC
