### ISSUE TITLE
Unhandled 'error' event when watchman hasn't been installed 

### ISSUE THREAD

**Issue by atainton** [coryhouse/react-slingshot#437] opened 2017-05-25 08:55 UTC
It took me a while to figure this out but after running npm start -s the startup process would be terminated and the following error:

> Error: Error watching file for changes: EMFILE
>     at exports._errnoException (util.js:1033:11)
>     at FSEvent.FSWatcher._handle.onchange (fs.js:1375:11)

I did a bit of searching and I found out that this is a watchman issue. After discovering this I ran brew install watchman and ran npm start -s again and everything worked.

It may be worthwhile adding this to the readme as one of the troubleshooting options.

Node version:
7.7.2

npm version:
4.1.2

Operating system:
MacOS Sierra

Command line used:
iterm

Steps to reproduce:
npm run setup
npm start -s

**Comment by kwelch** [comment] 2017-05-25 11:54
Did you make any changes to slingshot before this issue occurred of was this with a fresh clone of slingshot? 

I am not using node v7, so that is another potential cause.

**Comment by nickytonline** [comment] 2017-06-05 02:28
@atainton, just following up on this. Are you still having the issue and if so, as @kwelch asked, are you using a fresh clone of react-slingshot?

**Comment by AntonyBaasan** [comment] 2017-07-12 04:33
Had the same issue. MacOS. Thanks

**Comment by kwelch** [comment] 2017-07-12 12:40
@AntonyBaasan  Was this a fresh clone? What node/npm version are you running?

**Comment by liutongchen** [comment] 2017-07-12 22:08
I run into the same issue today when I clone slingshot, which didn't happen before.

npm version: 5.2.0
node version: 6.10.1
Operating system: MacOS Sierra

**Comment by coryhouse** [comment] 2017-07-13 01:47
@AntonyBaasan Are you saying the steps outlined by @atainton resolved your issue?

**Comment by tkachenko1503** [comment] 2017-07-14 05:32
Im using a fresh clone and had the same issue.
Without `-s` flag I see this log
```
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test" "--" "--watch"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! sl-cloud@0.1.0 test: `jest "--watch"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sl-cloud@0.1.0 test script 'jest "--watch"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sl-cloud package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest "--watch"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sl-cloud
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sl-cloud
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/s.tkachenko/Desktop/work/sl-cloud/npm-debug.log

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "test:watch"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! sl-cloud@0.1.0 test:watch: `npm run test -- --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sl-cloud@0.1.0 test:watch script 'npm run test -- --watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sl-cloud package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run test -- --watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sl-cloud
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sl-cloud
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/s.tkachenko/Desktop/work/sl-cloud/npm-debug.log
ERROR: "test:watch" exited with 1.

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! sl-cloud@0.1.0 start: `npm-run-all --parallel test:watch open:src lint:watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sl-cloud@0.1.0 start script 'npm-run-all --parallel test:watch open:src lint:watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sl-cloud package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel test:watch open:src lint:watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sl-cloud
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sl-cloud
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/s.tkachenko/Desktop/work/sl-cloud/npm-debug.log
```

**Comment by kwelch** [comment] 2017-07-14 06:23
I looked up the `jest` docs and it appears that by default it uses `watchman` to crawl through the files. 

It is possible to disabled this feature by passing the `--no-watchman` to the `jest` command, or install `watchman`. 

I agree with @atainton  that this may be a documentation point, but it is not a bug of slingshot (directly)

A PR to add this to the docs would be appreciated 👍, but for now (unless someone see otherwise) I am going to close this.

**Closed by kwelch** 2017-07-14 06:23 UTC

**Comment by coryhouse** [comment] 2017-07-14 12:32
Here's a link to the relevant docs: https://facebook.github.io/jest/docs/troubleshooting.html#watchman-issues

**Comment by kwelch** [comment] 2017-07-14 13:36
Thanks, I had that issue in my clipboard, but apparently it was a little late and I forgot 😅
