### ISSUE TITLE
Breakpoints not getting hit on initial page load in Chrome Dev Tools

### ISSUE THREAD

**Issue by nhalloran** [coryhouse/react-slingshot#19] opened 2016-01-12 21:14 UTC
Thanks for this great toolkit!

I am having some problems debugging using Chrome Dev Tools. Breakpoints are not working.

The source maps are working - i.e. I can navigate the code files ok. I have tried with and without the React Dev Toole extension enabled, and I have cleared my cache, but no luck.

Googling and searching on StackOverflow gives me the impression that it may have to do with the fact that React Slingshot saves source maps to memory, not to file. I've seen discussion on clearing my workspace folder - I have no workspace folder specified. Should there be?

Thanks for the help,
Neil

**Comment by coryhouse** [comment] 2016-01-12 22:46
As you can see, it works for me. Can you try setting a breakpoint on this same spot I'm hitting in my screenshot and see if it sticks? Be sure to note that I'm setting a breakpoint on the file under webpack:// 

<img width="1920" alt="screen shot 2016-01-12 at 4 41 33 pm" src="https://cloud.githubusercontent.com/assets/1688997/12279197/746ebb7a-b94b-11e5-9db8-eed7aab93a62.png">

**Comment by nhalloran** [comment] 2016-01-12 22:56
Thank you so much for the help. It must be something on my end. Here I try to break on that same line, with no luck.

<img width="1257" alt="screen shot 2016-01-12 at 5 54 17 pm" src="https://cloud.githubusercontent.com/assets/1732298/12279518/9fea6f10-b955-11e5-9587-0f51c5c03008.png">

**Comment by nickytonline** [comment] 2016-01-12 23:02
@nhalloran it works for me too. Sometimes a hard reload in Chrome does the trick. Also ensure that caching is disabled when Chrome dev tools are open.

**Comment by nhalloran** [comment] 2016-01-12 23:03
Oh!! 
I should also say that I am looking to break during the initial load. I do get a break on that line when I edit the form, triggering the action.  I do not get a break on lines of code that run during the init, for example:
<img width="1207" alt="screen shot 2016-01-12 at 6 00 25 pm" src="https://cloud.githubusercontent.com/assets/1732298/12279698/b5666fbe-b956-11e5-8177-1a5c4aacb886.png">

**Comment by coryhouse** [comment] 2016-01-13 03:37
Yes, I can confirm that break points aren't getting hit on initial page load. Perhaps a different source-map setting in Webpack will resolve that. Another simple approach: Just type `debugger` and it'll hit that breakpoint on load just fine.

**Comment by coryhouse** [comment] 2016-01-13 04:05
I just confirmed that the production build honors breakpoints just fine, so this is indeed related to the webpack devtool setting. For the prod build the starter kit uses `source-map` which works fine. `eval-source-map` doesn't hit breakpoints on load. I've confirmed switching the devtool setting to `eval` fixes this bug. Per the docs, `eval` also runs faster: https://webpack.github.io/docs/configuration.html#devtool

**Comment by nhalloran** [comment] 2016-01-13 16:35
Good to know. The `debugger` command is a great workaround. Thanks!

Also note that I tested it with the official redux examples, i.e.
https://github.com/rackt/redux/tree/master/examples/counter
...and the behavior is the same, so it's clearly a pretty general "issue" - perhaps not necessary to track here.

Thanks again - building my app on this!

**Comment by coryhouse** [comment] 2016-01-13 20:51
Given your comment, I'm going to leave the debugger setting as is for now and close this issue. The eval devtool supports breakpoints on load, but provides a less useful debugging experience otherwise. So I don't see any good changes to make. Thankfully, `debugger` effectively works around the admitted quirk. Thanks!

**Closed by coryhouse** 2016-01-13 20:51 UTC

**Comment by raythree** [comment] 2016-08-25 21:13
I just came across this because I was having the same issue. This setting worked fixed the issue:
```
devtool: '#inline-source-map'
```
