### ISSUE TITLE
Unexpected token import in all specs

### ISSUE THREAD

**Issue by sunvar** [coryhouse/react-slingshot#402] opened 2017-04-01 03:10 UTC
Node version:
v7.8.0

npm version:
4.2.0

Operating system:
ubuntu 16.04

Steps to reproduce:
$ git clone https://github.com/coryhouse/react-slingshot.git
$ npm run setup
$ npm start -s
$ NODE_ENV=development

All of the above commands work fine and produce an application on port 3000. However running the build for creating a distribution seem to fail on unexpected token import for all the unit test specs.
$ npm run build

* Executing npm run build fails on build. Here is the full log..
---
npm run build

> react-slingshot@5.0.0 prebuild /home/sanjay/git/github/react-slingshot
> npm run clean-dist && npm run lint && npm run test

> react-slingshot@5.0.0 clean-dist /home/sanjay/git/github/react-slingshot
> npm run remove-dist && mkdir dist

> react-slingshot@5.0.0 remove-dist /home/sanjay/git/github/react-slingshot
> rimraf ./dist

> react-slingshot@5.0.0 lint /home/sanjay/git/github/react-slingshot
> esw webpack.config.* src tools --color

✓ Clean (11:04:04 PM)

> react-slingshot@5.0.0 test /home/sanjay/git/github/react-slingshot
> jest

 FAIL  src/components/FuelSavingsTextInput.spec.js
  ● Test suite failed to run

    /home/sanjay/git/github/react-slingshot/src/components/FuelSavingsTextInput.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)

 FAIL  src/components/FuelSavingsForm.spec.js
  ● Test suite failed to run

    /home/sanjay/git/github/react-slingshot/src/components/FuelSavingsForm.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)

 FAIL  src/containers/FuelSavingsPage.spec.js
  ● Test suite failed to run

    /home/sanjay/git/github/react-slingshot/src/containers/FuelSavingsPage.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)

 FAIL  src/components/FuelSavingsResults.spec.js
  ● Test suite failed to run

    /home/sanjay/git/github/react-slingshot/src/components/FuelSavingsResults.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)

 FAIL  src/utils/fuelSavingsCalculator.spec.js
  ● Test suite failed to run

    /home/sanjay/git/github/react-slingshot/src/utils/fuelSavingsCalculator.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import calculator from './fuelSavingsCalculator';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)

 FAIL  src/components/AboutPage.spec.js
  ● Test suite failed to run

    /home/sanjay/git/github/react-slingshot/src/components/AboutPage.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)

 FAIL  src/utils/dateHelper.spec.js
  ● Test suite failed to run

    /home/sanjay/git/github/react-slingshot/src/utils/dateHelper.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { getFormattedDateTime } from './dateHelper';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)

 FAIL  src/utils/numberFormatter.spec.js
  ● Test suite failed to run

    /home/sanjay/git/github/react-slingshot/src/utils/numberFormatter.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import NumberFormatter from './numberFormatter';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)

 FAIL  src/reducers/fuelSavingsReducer.spec.js
  ● Test suite failed to run

    /home/sanjay/git/github/react-slingshot/src/reducers/fuelSavingsReducer.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as ActionTypes from '../constants/actionTypes';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)

 FAIL  src/actions/fuelSavingsActions.spec.js
  ● Test suite failed to run

    /home/sanjay/git/github/react-slingshot/src/actions/fuelSavingsActions.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as ActionTypes from '../constants/actionTypes';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)

 FAIL  src/store/store.spec.js
  ● Test suite failed to run

    /home/sanjay/git/github/react-slingshot/src/store/store.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as ActionTypes from '../constants/actionTypes';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)

 FAIL  src/utils/mathHelper.spec.js
  ● Test suite failed to run

    /home/sanjay/git/github/react-slingshot/src/utils/mathHelper.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import MathHelper from './mathHelper';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)

Test Suites: 12 failed, 12 total
Tests:       0 total
Snapshots:   0 total
Time:        1.889s
Ran all test suites.

npm ERR! Linux 4.4.0-70-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-slingshot@5.0.0 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-slingshot@5.0.0 test script 'jest'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-slingshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-slingshot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-slingshot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sanjay/.npm/_logs/2017-04-01T03_04_07_640Z-debug.log

npm ERR! Linux 4.4.0-70-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-slingshot@5.0.0 prebuild: `npm run clean-dist && npm run lint && npm run test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-slingshot@5.0.0 prebuild script 'npm run clean-dist && npm run lint && npm run test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-slingshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean-dist && npm run lint && npm run test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-slingshot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-slingshot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sanjay/.npm/_logs/2017-04-01T03_04_07_657Z-debug.log

**Comment by coryhouse** [comment] 2017-04-01 21:03
Hrm. I don't have Ubuntu handy to check. Try deleting node_modules and reinstalling.

**Comment by nickytonline** [comment] 2017-04-01 23:25
@sunvar, I have Ubuntu 16.10 on my work machine and react-slingshot runs fine for all npm scripts. Your errors appear to be complaining about `import` statements which lead me to believe you're having issues with babel.

* I'll ask the obvious first. Have you run `yarn` or `npm install`?
* Please have a look at the [FAQ](https://github.com/coryhouse/react-slingshot/blob/master/docs/FAQ.md)
* If you're still stuck, can you provide a repo that I can clone the repo?

Thanks,
Nick

**Comment by kwelch** [comment] 2017-04-03 13:33
`Token import` sounds like a babel issue. Can you ensure you share your `.babelrc` file?

**Comment by sunvar** [comment] 2017-04-03 16:07
All, thanks for responding. Your help is deeply appreciated. 

@nickytonline 
First of all, I was able to get react-slingshot working in the past. So, I am definetely not new to this awesome starter kit. I have also finished coryhouse's pluralsight courses on flux and redux.
Anyways, I am pretty sure I have deleted my cloned repository multiple times, and reran "npm install". 
Let me also try to do this on a mac which I don't use often. I will post you the results in the evening.  

@kwelch The babelrc file I used came with the react-slingshot repo. So, I am not sure if you are referring to a global babelrc which I don't have one in my home directory.

**Comment by sunvar** [comment] 2017-04-04 00:46
Ok. I am not sure what happened. But I am unable to reproduce this issue with imports. 

However during my testing, I found the following issue. I had to disable to hmr preset to resolve this error and get my "run run build" working. Please mark my original issue as resolved with imports.


 FAIL  src/containers/FuelSavingsPage.spec.js
  ● Test suite failed to run

    locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr
      
      at proxyReactComponents (node_modules/react-transform-hmr/lib/index.js:51:11)
      at Object.<anonymous> (src/components/FuelSavingsForm.js:3:1325)
      at Object.<anonymous> (src/containers/FuelSavingsPage.js:5:50)
      at Object.<anonymous> (src/containers/FuelSavingsPage.spec.js:3:50)

 FAIL  src/components/FuelSavingsForm.spec.js
  ● Test suite failed to run

    locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr
      
      at proxyReactComponents (node_modules/react-transform-hmr/lib/index.js:51:11)
      at Object.<anonymous> (src/components/FuelSavingsForm.js:3:1325)
      at Object.<anonymous> (src/components/FuelSavingsForm.spec.js:3:50)

Test Suites: 2 failed, 10 passed, 12 total
Tests:       47 passed, 47 total
Snapshots:   1 passed, 1 total
Time:        2.281s
Ran all test suites.

npm ERR! Linux 4.4.0-71-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-slingshot@5.0.0 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-slingshot@5.0.0 test script 'jest'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-slingshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-slingshot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-slingshot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sanjay/.npm/_logs/2017-04-04T00_44_50_309Z-debug.log

npm ERR! Linux 4.4.0-71-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-slingshot@5.0.0 prebuild: `npm run clean-dist && npm run lint && npm run test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-slingshot@5.0.0 prebuild script 'npm run clean-dist && npm run lint && npm run test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-slingshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean-dist && npm run lint && npm run test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-slingshot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-slingshot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sanjay/.npm/_logs/2017-04-04T00_44_50_332Z-debug.log

**Comment by nickytonline** [comment] 2017-04-04 02:37
@sunvar, is your new issue related to https://github.com/gaearon/react-transform-hmr/issues/5 ? If so, see the solutions presented there. Otherwise, please open a new issue in our repo with a project we can clone to see what's up.

**Comment by sunvar** [comment] 2017-04-04 17:38
@nickytonline Correct, that seems to be the second issue I have been having. But looks like that's the solution I should look at instead of disabling the hmr in the babelrc for generating the distribution. Thank you.

**Comment by kaamoss** [comment] 2017-04-05 09:28
@sunvar @nickytonline I'm also having similar issues when tests re-run after file changes are detected:

```
 FAIL  resources/assets/js/src/components/FuelSavingsForm.spec.js
  ● Test suite failed to run

    locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr

      at proxyReactComponents (node_modules/react-transform-hmr/lib/index.js:51:11)
      at Object.<anonymous> (resources/assets/js/src/components/FuelSavingsForm.js:3:1320)
      at Object.<anonymous> (resources/assets/js/src/components/FuelSavingsForm.spec.js:3:50)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:191:7)
      at process.nextTick (internal/child_process.js:744:12)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        2.106s
```

**Comment by bigjollygiant14** [comment] 2017-07-20 20:26
We're encountering the same issue. We have the same `package.json`s and node versions, but after `npm install`, I run `npm run test` and it works, but another dev (with the exact same repo) gets the import error. Is there something we're missing. We've both tried different versions of node, and deleted and reinstalled the repo. Is there something else we can try?

**Comment by kwelch** [comment] 2017-07-21 02:33
Import errors from my experience are typically tied to babel. I would validate that your babel config is properly initialized within the project.

**Comment by bigjollygiant14** [comment] 2017-07-21 16:03
We figured it out last night. To resolve, we did `npm install --save-dev babel-preset-es2015` and changed the babel development presets to `"presets": ["env", "es2015", "react-hmre"]`. We tried with other developers and it was about 50/50 whether it worked for them or not. I'm wondering if this is a change that now needs to be made to slingshot. We got down to making sure we had the same `NODE_ENV`, node versions, wiping all globally installed packages, changing our bash profiles, but it always worked for me and never worked (until we added the babel preset and changed the babel config) for the other developer. With this added, everyone was up to 100%. Hopefully, anyone that runs into this in the future can resolve it in a similar fashion.

**Comment by coryhouse** [comment] 2017-07-21 20:54
@bigjollygiant14 - Thanks for sharing! I'm curious, does it work if you run babel-preset-latest instead of env and es2015? 

I ask because [env is supposed to do the same thing as babel-preset-latest by default](https://github.com/babel/babel-preset-env#support-all-plugins-in-babel-that-are-considered-latest).

**Comment by coryhouse** [comment] 2017-07-21 21:13
I've reopened this issue because I think I may have a fix. We weren't being explicit about the env config. Can you try [this PR]()? Does it resolve your issue @bigjollygiant14?

**Comment by nickytonline** [comment] 2017-12-29 05:27
@bigjollygiant14, just following up on this as we're almost in 2018 ;) Was your issue resolved with the PR that @coryhouse mentions in his previous comment?

**Comment by bigjollygiant14** [comment] 2017-12-29 19:51
I will check it out today, but I'm not sure it's much help since it always worked on my machine. I can ask the developer that was having issues when we're back in the office next week. Thanks again for reaching out.

**Comment by bigjollygiant14** [comment] 2017-12-29 19:55
The link Cory posted only goes to this issue and not to a PR, but I will try by changing the env config.

**Comment by nickytonline** [comment] 2018-04-06 04:11
@bigjollygiant14, are you still having issues with this?

**Comment by bigjollygiant14** [comment] 2018-04-11 13:47
Yep. I just used the template again and everything worked. Thank you, everyone.

**Comment by nickytonline** [comment] 2018-04-11 13:50
Glad to hear all is good @bigjollygiant14 👍

**Closed by nickytonline** 2018-04-11 13:50 UTC

**Comment by jamiewhittle** [comment] 2018-11-14 11:46
I am having the same issue.

Node version:
v8.11.4

npm version:
5.6.0

Operating system:
Windows 10

Steps to reproduce:
$ git clone https://github.com/coryhouse/react-slingshot.git
$ npm run setup
$ npm start -s
