### ISSUE TITLE
Including third party modules

### ISSUE THREAD

**Issue by wormyy** [coryhouse/react-slingshot#48] opened 2016-02-06 20:36 UTC
Hello I am starting an app with your starter kit. I wanted to include normalize.css and react-toolbox but I am getting these errors during the build:

```
ERROR in ./~/normalize.css/normalize.css
Module parse failed: /home/jules/projects/tourbnb-frontend/node_modules/normalize.css/normalize.css Line 9: Unexpected token {
You may need an appropriate loader to handle this file type.
|  */
| 
| html {
|   font-family: sans-serif; /* 1 */
|   -ms-text-size-adjust: 100%; /* 2 */
 @ ./src/index.js 29:0-24

ERROR in ./~/react-toolbox/lib/app/App.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./style in /home/jules/projects/tourbnb-frontend/node_modules/react-toolbox/lib/app
 @ ./~/react-toolbox/lib/app/App.js 11:13-31
```

This is my index.js: 
```
import React from 'react';
import {render} from 'react-dom';
import { Provider } from 'react-redux';
import ToolboxApp from 'react-toolbox/lib/app';
import App from './containers/App';
import configureStore from './store/configureStore';
import './styles/styles.scss'; //Yep, that's right. You can import SASS/CSS files too! Webpack will run the associated loader and plug this into the page.
import 'normalize.css';

const store = configureStore();

render(
  <Provider store={store}>
    <ToolboxApp>
      <App />
    </ToolboxApp>
  </Provider>, document.getElementById('app')
);
```

I am fairly new to react and webpack, so I am sorry if it's something really obvious.

**Comment by coryhouse** [comment] 2016-02-06 21:25
I'm not familiar with normalize.css, but it appears the issue is either:
1. It's referencing a file that it cannot find. Check your paths.
2. It's referencing a file type that webpack isn't currently setup to load. 

If it's 2, then check you'll just need to find the appropriate webpack loader for the file being loaded.

**Comment by wormyy** [comment] 2016-02-06 21:43
But normalize is just a css file, that should be handled by this loader, shouldn't it?
```
loaders.push({
      test: /(\.css|\.scss)$/,
      include: path.join(__dirname, 'src'),
      loaders: ['style', 'css?sourceMap', 'sass?sourceMap']
    });
```

I realized that if I change path `path.join(__dirname, 'src')` to `path.join(__dirname)` it loads properly. 

However the react-toolbox problem still persists.

**Comment by coryhouse** [comment] 2016-02-06 21:56
It's looking in /src so you'll need to place your files there too.

**Comment by wormyy** [comment] 2016-02-06 23:26
But I want to be able to import from node_modules. Is not that the way I am supposed to get third party packages?

**Comment by coryhouse** [comment] 2016-02-07 01:53
Ah, I've removed the include: from the css loader. It was unnecessary and, yes, it would have excluded node_modules. Thanks for opening the issue!

**Comment by coryhouse** [comment] 2016-02-07 01:53
Fix committed.

**Closed by coryhouse** 2016-02-07 01:53 UTC
