### ISSUE TITLE
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

### ISSUE THREAD

**Issue by shankardevy** [coryhouse/react-slingshot#67] opened 2016-03-05 18:13 UTC
Cloning the master and running `npm start -s` gives this error message on Safari and the site doesn't get loaded.

**Comment by coryhouse** [comment] 2016-03-05 19:19
What do you see on the command line after running npm start -s?

**Comment by acidbluebriggs** [comment] 2016-03-05 20:07
Same issue here. Output of `npm start -s` is simply:

> react-slingshot@1.2.0 prestart /Users/mmiller/Development/Playground/react-slingshot
> npm run remove-dist


> react-slingshot@1.2.0 remove-dist /Users/mmiller/Development/Playground/react-slingshot
> rimraf ./dist


> react-slingshot@1.2.0 start /Users/mmiller/Development/Playground/react-slingshot
> parallelshell "npm run lint:tools" "npm run test:watch" "npm run open:src" "-s"


> react-slingshot@1.2.0 test:watch /Users/mmiller/Development/Playground/react-slingshot
> npm run test -- --watch


> react-slingshot@1.2.0 lint:tools /Users/mmiller/Development/Playground/react-slingshot
> eslint webpack.config.js tools


> react-slingshot@1.2.0 open:src /Users/mmiller/Development/Playground/react-slingshot
> babel-node tools/srcServer.js


> react-slingshot@1.2.0 test /Users/mmiller/Development/Playground/react-slingshot
> cross-env NODE_ENV=test mocha --reporter progress --compilers js:babel-core/register --recursive "./src/**/*.spec.js" "--watch"


[?25l
  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬]

  29 passing (72ms)

[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.70:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.70:3001
 -------------------------------------
[BS] Serving files from: src
[BS] Watching files...
webpack built f9bd242d12dfdfedcad6 in 5209ms
[?25h

**Comment by coryhouse** [comment] 2016-03-06 02:47
Odd. So where are you seeing the error listed in the subject of this issue? 

Also, some questions to help reproduce:

1. Operating System
2. Node version

**Comment by acidbluebriggs** [comment] 2016-03-06 16:25
Node: 5.0.0
OS X: 10.11.3
Safari: 9.0.3

**Comment by yunai** [comment] 2016-03-06 18:55
Me too.
Node: 5.7.1
OS X: 10.11.3
Safari: 9.0.3

3Q

not work：
`
class DoctorPage extends React.Component {
  render() {

    return (
      <div>
        </div>
    );
  }
}
`

work：
`
const DoctorPage = (props) => {
  return (
    <div>
    </div>
  );
};
`

**Comment by coryhouse** [comment] 2016-03-06 21:22
I'm running Node 5 on OSX and not seeing this. Can you clarify, is this issue occurring with no changes to the repo?

**Comment by acidbluebriggs** [comment] 2016-03-07 13:58
Strange. I pulled the repo again, and its now running in Safari. I even went back a couple commits and no issues. I'll play around again and see if I can find out what is causing the offending `const` to be introduced. I'm pretty sure it's Babel doing this. It could be something like WebPack, but I am just throwing that out there. Will update you if/when this creeps up.

**Comment by coryhouse** [comment] 2016-03-18 22:03
Anyone still experiencing this? If not, I'd like to close since I haven't been able to repro.

**Comment by coryhouse** [comment] 2016-03-21 11:53
Closing since no one is reporting continued issues. Please reply if you experience again.

**Closed by coryhouse** 2016-03-21 11:53 UTC

**Comment by acidbluebriggs** [comment] 2016-03-21 19:13
Hey, thanks for closing. I completely forgot to respond to your request for comments. I am no longer seeing the error. Thanks for all of your work.
