### ISSUE TITLE
Can't use Internet Explorer as development browser 

### ISSUE THREAD

**Issue by stuartdga** [coryhouse/react-slingshot#26] opened 2016-01-19 13:10 UTC
The sample app renders but the app does not render the results when the form is completed.

**Comment by coryhouse** [comment] 2016-01-19 14:29
Great catch. Reproduced. I'm investigating now.

**Comment by coryhouse** [comment] 2016-01-19 15:47
Per the console message in IE: webpack-hot-middleware's client requires EventSource to work. You should include a polyfill if you want to support this browser: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#Tools

**Comment by coryhouse** [comment] 2016-01-19 20:29
After further testing, the example app was also not running in IE when built because of a separate issue - I was using Object.assign in the example app. I've just committed a fix for that. So this means IE will now work fine in production mode (when you run this):
`npm run build`

If you want to do dev in IE, read my previous comment. (Again, still considering what commit I want to make to support doing dev in IE)

**Comment by stuartdga** [comment] 2016-01-19 20:30
Thanks, I can try that.  The bigger issue for me was that browser-sync ignored my browser option in the client config.  I'll research a little more this evening.

**Comment by coryhouse** [comment] 2016-02-29 17:49
@stuartdga Did you have any luck getting HMR to work in IE? I've tried adding in the suggested polyfill and hot module reloading still doesn't work in IE. It initially connects, but throws an error on save.

**Comment by stuartdga** [comment] 2016-02-29 18:02
No, I changed my default browser to Chrome and changed it back after i completed the course.

**Comment by coryhouse** [comment] 2016-02-29 18:59
Gothca. Alright, I'm going to close this as "Won't fix" since polyfills are available for the few who want hot reloading in IE.

**Closed by coryhouse** 2016-02-29 18:59 UTC
Labels: bug, wontfix
