### ISSUE TITLE
error watching file exception, preventing npm start from working + fix

### ISSUE THREAD

**Issue by polaire801** [coryhouse/react-slingshot#520] opened 2017-12-23 21:46 UTC
This appears to be similar to issue #437, which was closed, but I just experienced the same issue on a new mac (today, 12/23/17). I vaguely recall running into this issue on another machine a few months ago (also mac).

I followed the installation instructions and troubleshooting section, but would run into an error when executing 'npm start -s'.

I searched on the error text and found this article that mentions the error and suggests a fix.
https://stackoverflow.com/questions/39675840/error-watching-file-for-changes-emfile-when-run-the-examples-from-facebook-re

at the very least, I think it would be helpful to include a bullet point in the README's troubleshooting section for this issue.

if it helps..
npm version: 5.6.0
node version: 9.3.0
os: mac high sierra 10.13.2

Thanks!

**Comment by nickytonline** [comment] 2017-12-24 14:40
PRs for documentation are always welcome. 😀

**Comment by nickytonline** [comment] 2017-12-24 21:27
Didn't read the fix in SO. Actually, I think the watchman fix has been mentioned/documented elsewhere. @kylewelch?

**Comment by perchrh** [comment] 2017-12-25 20:23
Had the same problem, and the fix was to install watchman, like described here https://github.com/facebookincubator/create-react-app/issues/2393
I recommend to mention this watchman-related fix in the same section as the Linux watch issue is described, with the sysctl workaround command

**Comment by nickytonline** [comment] 2017-12-29 05:09
Whoever would like to PR for the docs, feel free to do so. I think @kwelch had planned on doing this, https://github.com/coryhouse/react-slingshot/issues/469#issuecomment-331927311, but I think he got busy. Kyle?

**Comment by nickytonline** [comment] 2017-12-29 05:15
Duplicate of of #437, #449, #469 which are all closed but leaving this open as we'll document how to fix it here.

**Comment by polaire801** [comment] 2017-12-29 19:58
I'm a github n00b, but I'd be happy to make something like this my first github PR. :)

**Comment by nickytonline** [comment] 2017-12-30 00:01
Sounds good @polaire801. Hit me up if you need a hand

**Comment by paulfreeman** [comment] 2018-02-02 13:43
On Mac OS High Sierra had this problem.  Reinstalling watchman with brew solved the problem apropos https://github.com/react-community/create-react-native-app/issues/281

**Comment by nickytonline** [comment] 2018-02-06 02:03
Closing this as it was documented in #536.

**Closed by nickytonline** 2018-02-06 02:03 UTC
Labels: Good first PR, documentation, help wanted
